[package]
name = "polodb_core"
version = "0.4.0"
authors = ["Vincent Chan <okcdz@diverse.space>"]
license = "MIT"
edition = "2018"
repository = "https://github.com/vincentdchan/PoloDB"
description = "PoloDB is a embedded JSON-based database"

[lib]
name="polodb_core"
path="lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
#lazy_static = "1.4.0"
polodb_bson = "0.2.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["fileapi"] }

[features]
default = []

log = []
